### ISSUE TITLE
请问项目是怎么启动的

### ISSUE THREAD

**Issue by wwe1428103707** [ZhouBoXiao/SolidityObfuscator#1]
您好，在执行/src/test.py后，报错显示ImportError: No module named parser.SolidityLexer
似乎solidityobf目录下少了很多东西，请问要怎么获得
希望知道项目应该怎么运行，需要哪些组件？

**Comment by ZhouBoXiao** [comment]
您好，请查看/src/Makefile，需要执行make antlr4来生成SolidityLexer

**Comment by wwe1428103707** [comment]
谢谢您，问题已解决
